services:
  postgres:
    hostname: postgresHost
    container_name: Postgres
    image: postgres:14.3
    restart: always
    ports: 
      - 5432:5432
    environment:      
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_DATABASE}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - v-postgres:/var/lib/postgresql/data

  spring-api:
    container_name: Spring-API
    working_dir: /app
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 8080:8080          
    environment:
      spring.datasource.url: ${DB_PATH}
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
    command: ./mvnw spring-boot:run  
    volumes:   
      - ./:/app
      - .m2:/root/.m2
      - type: volume
        source: v-spring-api
        target: /root
volumes:
  v-spring-api:
  v-postgres:
