server:
  port: ${SERVER_PORT}

spring:
    datasource:
      jdbc-url: ${DB_PATH}
      url: ${DB_PATH}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${ISSUER_URI}
            jwk-set-uri: http://localhost:8080/auth/realms/pagrn/protocol/openid-connect/certs
        client:
          registration:
            keycloak:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}
              authorization-grant-type: password
              provider: keycloak
              scope: openid, profile, roles
          provider:
            keycloak:
              issuer-uri: ${ISSUER_URI}
              authorization-uri: http://localhost:8080/auth/realms/pagrn/protocol/openid-connect/auth
              token-uri: http://localhost:8080/auth/realms/pagrn/protocol/openid-connect/token
              user-info-uri: http://localhost:8080/auth/realms/pagrn/protocol/openid-connect/userinfo

keycloak:
  realm: ${REALM}
  resource: ${CLIENT_ID}
  auth-server-url: ${AUTH_SERVER_URL}
  ssl-required: external
  public-client: true
  use-resource-role-mappings : false
  bearer-only: true

pagrn-auth-data:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/keycloak
    url: jdbc:postgresql://localhost:5432/keycloak
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    auto-commit: false