package KieRule;
import br.gov.sead.motorDeCalculo.model.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List
import java.util.Date
import java.math.MathContext
import java.math.RoundingMode;
import br.gov.sead.motorDeCalculo.repository.*;
import java.util.stream.Collectors;
import java.time.LocalDate;
import java.time.*;
import java.time.format.DateTimeFormatter;


rule "Vencimento base (01/01/2022 - 31/12/2022)"
    when
        $servidor : Snapshot($servidor.verificaVigencia("01-01-2022", "31-12-2022") == true);
    then
        $servidor.addVantagemDesconto(new VantagemDesconto("001", $servidor.getRemuneracaoBase(), $servidor.getVigencia()));
        $servidor.setBruto($servidor.getBruto().add($servidor.getRemuneracaoBase()));
    end;


